version: "3.9"

services:
  indexer_app:
    container_name: indexer_app
    build: .
    ports:
      - "80:3000"
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - START_BLOCK=${START_BLOCK}
      - PORT=${PORT}
      - PRIVATE_KEY=${PRIVATE_KEY}
      - ORDERBOOK_ID=${ORDERBOOK_ID}
      - PERP_MARKET_ID=${PERP_MARKET_ID}
      - CLEARING_HOUSE_ID=${CLEARING_HOUSE_ID}
      - ACCOUNT_BALANCE_ID=${ACCOUNT_BALANCE_ID}
    depends_on:
      - indexer_database

  indexer_database:
    container_name: indexer_database
    image: postgres:16
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - indexer_database_data:/var/lib/postgresql/data

volumes:
  indexer_database_data: {}
