version: "3.9"

services:
  indexer_app:
    container_name: indexer_app
    build: .
    ports:
      - "80:3000"
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - CONTRACT_ID=${CONTRACT_ID}
      - START_BLOCK=${START_BLOCK}
      - PORT=${PORT}
      - PRIVATE_KEY=${PRIVATE_KEY}
    depends_on:
      - orderbook_indexer_database

  orderbook_indexer_database:
    container_name: orderbook_indexer_database
    image: postgres:16
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - orderbook_indexer_database_data:/var/lib/postgresql/data

volumes:
  orderbook_indexer_database_data: {}
