version: "3.9"

services:
  indexer_app:
    container_name: indexer_app
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_NAME=indexer_db
      - DB_USER=francesco
      - DB_PASSWORD=%e\/fOnoM5
      - DB_HOST=indexer_database
      - CONTRACT_ID=0x72175cdd41bbf890f8cddfe54fa55ac0f311f963c010746337f1c2ac3d79ffbb
      - START_BLOCK=8851676
      - PORT=3000
      - PRIVATE_KEY=PK_PK_PK
    depends_on:
      - indexer_database

  indexer_database:
    container_name: indexer_database
    image: postgres:16
    environment:
      - POSTGRES_DB=indexer_db
      - POSTGRES_USER=francesco
      - POSTGRES_PASSWORD=%e\/fOnoM5
    volumes:
      - indexer_database_data:/var/lib/postgresql/data

volumes:
  indexer_database_data: {}
